avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -I. -I./../Crypto -DKYBER_K=$1 -DSECRET_KEY_VARIANT=$2 -DUse_Deterministic_RNG=$3 cbd.cpp -o cbd.o
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -I. -I./../Crypto -DKYBER_K=$1 -DSECRET_KEY_VARIANT=$2 -DUse_Deterministic_RNG=$3 randombytes.cpp -o randombytes.o
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -I. -I./../Crypto -DKYBER_K=$1 -DSECRET_KEY_VARIANT=$2 -DUse_Deterministic_RNG=$3 matacc.cpp -o matacc.o
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -I. -I./../Crypto -DKYBER_K=$1 -DSECRET_KEY_VARIANT=$2 -DUse_Deterministic_RNG=$3 poly.cpp -o poly.o
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -I. -I./../Crypto -DKYBER_K=$1 -DSECRET_KEY_VARIANT=$2 -DUse_Deterministic_RNG=$3 polyvec.cpp -o polyvec.o
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -I. -I./../Crypto -DKYBER_K=$1 -DSECRET_KEY_VARIANT=$2 -DUse_Deterministic_RNG=$3 indcpa.cpp -o indcpa.o
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -I. -I./../Crypto -DKYBER_K=$1 -DSECRET_KEY_VARIANT=$2 -DUse_Deterministic_RNG=$3 ntt.cpp -o ntt.o
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -I. -I./../Crypto -DKYBER_K=$1 -DSECRET_KEY_VARIANT=$2 -DUse_Deterministic_RNG=$3 reduce.cpp -o reduce.o
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -I. -I./../Crypto -DKYBER_K=$1 -DSECRET_KEY_VARIANT=$2 -DUse_Deterministic_RNG=$3 symmetric.cpp -o symmetric.o
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -I. -I./../Crypto -DKYBER_K=$1 -DSECRET_KEY_VARIANT=$2 -DUse_Deterministic_RNG=$3 verify.cpp -o verify.o
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -I. -I./../Crypto -DKYBER_K=$1 -DSECRET_KEY_VARIANT=$2 -DUse_Deterministic_RNG=$3 crystalskyber.cpp -o crystalskyber.o
avr-gcc-ar rcs kyber_K$1_V$2_R$3.a cbd.o randombytes.o matacc.o poly.o polyvec.o indcpa.o ntt.o reduce.o symmetric.o verify.o crystalskyber.o
